# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Synth 8-685}  -string {{ERROR: [Synth 8-685] variable 'LED_segment' should not be used in output port connection [C:/Users/Gunte/Documents/Vivaldo/final_project/final_project.srcs/sources_1/new/top.v:20]}}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Gunte/Documents/Vivaldo/final_project/final_project.cache/wt [current_project]
set_property parent.project_path C:/Users/Gunte/Documents/Vivaldo/final_project/final_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  C:/Users/Gunte/Documents/Vivaldo/final_project/final_project.srcs/sources_1/new/Seven_segment_Decrementor.v
  C:/Users/Gunte/Documents/Vivaldo/final_project/final_project.srcs/sources_1/new/uart_tx.v
  C:/Users/Gunte/Documents/Vivaldo/final_project/final_project.srcs/sources_1/new/top.v
}
read_xdc C:/Users/Gunte/Documents/Vivaldo/final_project/final_project.srcs/constrs_1/new/constr.xdc
set_property used_in_implementation false [get_files C:/Users/Gunte/Documents/Vivaldo/final_project/final_project.srcs/constrs_1/new/constr.xdc]

synth_design -top top -part xc7a35tcpg236-1
write_checkpoint -noxdef top.dcp
catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
